### PR TITLE
Fix for entered search word not visible

### PR DESCRIPTION
**Pull request by montlikadani**
### Changes
* This PR should fixes that, when you typed something in the search field, the typed word can't be seen.

Screenshots
**Before**
kép
**After**
kép

### CODE REVIEW

**Comment by Snazzie** [comment]
Nice catch, whatever change they made broke the following override. 
```css
select, input:not(.btn-link), textarea {
    color: #eee !important;
}
```

Dont know why they're adding !important natively, github css practices make me cry sometimes...
Google makes me cry even more.

**Comment by montlikadani** [comment]
I don't know how do I fix that, and don't understand why it brokes an id/class in css.
I think the `!important` is required, to overwrite the site classes/ids if something is not working correctly and we don't have any idea on how to overwrite.

**Comment by Snazzie** [comment]
No, my comment isnt referred to your changes. i was refering to Github's CSS practice.
They shouldnt be using `!important` to override styles when they have access to source css, or the ability to just apply different classnames.

Our usage of !important to override existing style is nessesary.

**Comment by Snazzie** [comment]
i will merge this after i test it, probably later today.

**Comment by montlikadani** [comment]
Another catch:
- This "not visible" is affect for all sites that are on github, like github.com, github.com/user/repo

**Comment by Snazzie** [comment]
Thanks for contributing!

**Comment by xcasxcursex** [comment]
Works like a charm, thanks!

**Pull request merged**
