### PR TITLE
no background color for avatars

### LINKED ISSUE #197: background color for avatars should be unset
**Describe the bug**
White is used as the hardoded background for avatars.
This makes icons look very badly:

image

**Expected behavior**

image

**Screenshots**
see above

### PR DESCRIPTION
**Pull request by tessus**
### Changes
* Fixes #197

#### before
image

#### after
image

### CODE REVIEW

**Comment by tessus** [comment]
The build error has clearly nothing to do with the code change:

```
Failed to resolve action download info. Error: Unable to resolve action `ad-m/github-push-action@v0.4.0`, unable to find version `v0.4.0`
Retrying in 29.137 seconds
Failed to resolve action download info. Error: Unable to resolve action `ad-m/github-push-action@v0.4.0`, unable to find version `v0.4.0`
Retrying in 17.775 seconds
Error: Unable to resolve action `ad-m/github-push-action@v0.4.0`, unable to find version `v0.4.0`
```

**Comment by Snazzie** [comment]
I agree that white background sucks, but this was put in to solve #144

**Comment by Snazzie** [comment]
>The build error has clearly nothing to do with the code change:

CI pipeline has been broken since v0.4 of that action. thought it would work. clearly not, need to look into it again.

**Comment by tessus** [comment]
Hmm, In that case these orgs should use a proper icon. I think the normal use case is the other way round.

**Comment by tessus** [comment]
With the previous "fix" the theme breaks 99% of the icons. Somehow this makes no sense.

**Comment by Snazzie** [comment]
You know what, now i think of it again, i agree with you. :)

**Comment by tessus** [comment]
👍

**Comment by Snazzie** [comment]
🤦 it didnt come to my head that you didnt remove the css that forces the background lol. ill quickly do that

**Comment by tessus** [comment]
I've just noticed that.
I was wondering why it wasn't working. When I tested it I just added my code to the bottom locally.

I'm very sorry for that.

**Comment by Snazzie** [comment]
Dont worry about it haha, i should have tested it before merge. my fault really. :P  just pushed an update with the fix :)

**Pull request merged**
