### PR TITLE
Add a way to install from the Github repository to avoid userstyle.org

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**
This theme is great, but due to the privacy issue with "userstyle.org" and their owner "SimilarWeb" (See: https://en.wikipedia.org/wiki/Stylish#Privacy_issues ), it would be nice to have a way to install the userstyle directly from the repository.

This PR:
- Add a ```.user.styl``` that is detected by Stylus.
- Update the readme accordingly with an installation link.

This work is based on https://gitlab.com/vednoc/dark-gitlab

Note: If you don't merge this PR I will fork this project and maintain it myself because I refuse to use "userstyle.org" due to their past/present issue with privacy.

PS: "regex" isn't the best but I couldn't make it work with "domain".

Squash this PR when merging it.

### CODE REVIEW

**Comment by acoop133** [comment]
On holiday, sorry for getting to this a bit late :D

Ive heard about that. 

Thats pretty cool, i wasn't aware of stylus having such feature. 

I will give it a look and merge it when i find some time.

**Comment by acoop133** [comment]
Thanks for your contribution! :)

**Comment by acoop133** [comment]
see the new readme for install. i have changed the path

**Comment by acoop133** [comment]
I actually forgot to change update url in header.  i have done so now and the raw has updated. you will need reinstall it for the auto update to work :)

**Comment by TheFrenchGhosty** [comment]
Amazing! Thanks again for this theme!

**Pull request merged**
